# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# Custom BLE Name
CONFIG_ZMK_KEYBOARD_NAME="syr3x's corne"

# Better Bluetooth Connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep Settings (15 minutes)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
